# Generated by Django 4.2.13 on 2024-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('possible_answers_A', models.CharField(max_length=255)),
                ('possible_answers_B', models.CharField(max_length=255)),
                ('possible_answers_C', models.CharField(max_length=255)),
                ('possible_answers_D', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions_tbl',
            },
        ),
    ]
