# Generated by Django 4.2.13 on 2024-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='question_text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
