# Generated by Django 4.2.13 on 2024-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_triviaquestion_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='difficulty_level',
            field=models.CharField(default='easy', max_length=50),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
